In [3]:
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset
import torch
import tensorflow as tf

from tensorflow.keras import layers, models

import pandas as pd

In [ ]:


# 1. Load pre-trained tokenizer and model
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
d:\anaconda3_5\envs\envtda\lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

tensor([1, 1])

In [14]:

# 2. Prepare your data
# Example: using a custom dataset (replace this with your own data)
df=pd.read_csv('../datos/train_poll_v1s1.csv')
texts = df['respuestas'].tolist()
labels = df['ai'].tolist()

# Take only teh first 100 samples
texts = texts[:100]
labels = labels[:100]

# Separate by train and test
train_texts = texts[:int(len(texts)*0.8)]
train_labels = labels[:int(len(labels)*0.8)]
test_texts = texts[int(len(texts)*0.8):]
test_labels = labels[int(len(labels)*0.8):]

In [13]:

# Tokenize
encodings = tokenizer(train_texts, truncation=True, padding=True, return_tensors="pt")

# Create a dataset object
class SimpleDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    
    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item
    
    def __len__(self):
        return len(self.labels)

dataset = SimpleDataset(encodings, train_labels)

# 3. Set up Trainer
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    logging_dir="./logs",
    logging_steps=10,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
)

# 4. Train
trainer.train()

# 5. Predict
test_texts = ["I really like this product.", "I don't like this."]
test_encodings = tokenizer(test_texts, truncation=True, padding=True, return_tensors="pt")
outputs = model(**test_encodings)
predictions = torch.argmax(outputs.logits, dim=1)
print(predictions)  # 1 for positive, 0 for negative

d:\anaconda3_5\envs\envtda\lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

tensor([0, 0])

In [17]:
# Predict on test set
test_encodings = tokenizer(test_texts, truncation=True, padding=True, return_tensors="pt")
test_dataset = SimpleDataset(test_encodings, test_labels)
a=trainer.evaluate(test_dataset)

d:\anaconda3_5\envs\envtda\lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

In [24]:
outputs = model(**test_encodings)
predictions = torch.argmax(outputs.logits, dim=1)
print(predictions)  # 1 for positive, 0 for negative
print(test_labels)  # 1 for positive, 0 for negative
# print the accuracy

tensor([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0])
[0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0]

In [25]:
predictions =list(predictions.numpy())
test_labels = list(test_labels)
# print the accuracy
correct = 0
for i in range(len(predictions)):
    if predictions[i] == test_labels[i]:
        correct += 1
accuracy = correct / len(predictions)
print("Accuracy: ", accuracy)

Accuracy:  1.0

In [27]:
for i in range(len(test_texts)):
    print(test_texts[i], " : ", predictions[i], " : ", test_labels[i])

Que se vea que le apasione el tema y que pueda explicar temas difíciles con palabras sencillas   :  0  :  0
La unidad de medida de un segundo se define como la duración de 9.192.631.770 vibraciones del átomo de cesio-133. Esta se utiliza principalmente para medir el tiempo en diversas aplicaciones y campos, como en la física, la tecnología, la aviación, la navegación y en la industria de relojería, entre otros. También se utiliza en experimentos científicos para medir con precisión el tiempo de reacciones químicas, así como en la medicina para medir la frecuencia cardíaca y el tiempo de tratamiento de algunas enfermedades.  :  1  :  1
El día de la raza, porque es el día en que Cristóbal Colón llegó a América   :  0  :  0
-tareas realizadas
-evaluación de conocimientos
-proyecto
-disposicion de aprender
-participaciónes
-compromiso con el curso  :  0  :  0
Que no esté seco, que tenga un buen balances de sabores, ni muy dulce, ni muy amargo. Que no exageren con el betún. Que este bien horneado. Que utilzen ingredientes naturales.  :  0  :  0
El gobierno de México a nivel nacional está compuesto por tres poderes: ejecutivo, legislativo y judicial. El poder ejecutivo está encabezado por el presidente de la república, quien es el jefe de estado y de gobierno. El poder legislativo se compone por el senado y la cámara de diputados, encargados de crear y aprobar leyes. El poder judicial está conformado por el sistema de tribunales y jueces, encargados de interpretar y hacer cumplir las leyes.  :  1  :  1
Un segundo es una unidad de tiempo utilizada en varios sistemas de medida, definida como el periodo que pasa para que la luz recorra cierta distancia. Se utiliza para medir el tiempo desde el pasado hasta el futuro.  :  0  :  0
Ser responsable, dedicado y constante   :  0  :  0
La velocidad de un objeto en movimiento se define como la distancia que el objeto recorre en un período de tiempo determinado. Por lo tanto, la velocidad se mide en términos de distancia (como metros, kilómetros, millas, etc.) y tiempo (como segundos, minutos, horas, etc.). Una velocidad constante se mantiene si el objeto avanza la misma cantidad de distancia en el mismo tiempo durante todo su movimiento. La velocidad también puede ser calculada dividiendo la distancia recorrida por el tiempo que tardó en recorrerla.  :  1  :  1
Azucar  :  0  :  0
La calificación de un estudiante en un curso de ciencias (física, química, matemáticas) debe depender de varios factores, entre ellos su rendimiento académico en los exámenes y trabajos, su participación y esfuerzo en clase, su capacidad para aplicar los conceptos aprendidos en situaciones prácticas y su actitud hacia el aprendizaje y la mejora continua. También puede tenerse en cuenta el progreso que ha logrado el alumno a lo largo del curso y su capacidad de trabajar en equipo y cooperar con los demás estudiantes.  :  1  :  1
El gobierno de México a nivel nacional se compone de tres poderes: el ejecutivo, el legislativo y el judicial. El poder ejecutivo está encabezado por el presidente de la República y su función principal es llevar a cabo las políticas y programas de gobierno. El poder legislativo está conformado por el congreso, que se divide en dos cámaras: la de diputados y la de senadores, y su función es crear, modificar y aprobar leyes. El poder judicial está integrado por los tribunales y juzgados, y su función es aplicar las leyes y resolver conflictos legales.  :  1  :  1
Como modelo de inteligencia artificial, no tengo emociones ni una opinión personal sobre los realities televisivos. Sin embargo, puedo decir que son programas de televisión populares que atraen a una gran audiencia. Algunos espectadores pueden disfrutar de ver la competencia y el drama entre los participantes, mientras que otros pueden considerar que están sobrecargados de contenido poco realista o poco saludable. Por lo tanto, la respuesta a esta pregunta puede variar según la perspectiva individual del espectador.  :  1  :  1
La velocidad de un objeto se miden en m/s o cualquier distancia / tiempo. Esto te ayuda a ver cuánta distancia recorre el objeto en cierto tiempo.  :  0  :  0
Debe ser un estudiante que busca aprender, que es estudioso y da su mejor esfuerzo, es atento en clase y cuando tiene preguntas las hace, y que puede tener una buena relacion con el docente.  :  0  :  0
una distracción pero que entretiene  :  0  :  0
La calificación de un estudiante en un curso de ciencias, como física, química o matemáticas, debe depender de su capacidad para aplicar los conceptos y teorías aprendidos en situaciones prácticas. Además, debe demostrar su capacidad para resolver problemas y realizar cálculos precisos y exactos. La asistencia a clase, la participación en clase, los trabajos y exámenes también son factores importantes que se consideran al calificar a un estudiante. Finalmente, la actitud y el compromiso con su aprendizaje son esenciales para obtener una buena calificación.  :  1  :  1
El día de la raza. Es importante por la llegada de cristobal colon   :  0  :  0
De como lo maneje el profesor, la misma materia con un diferente profesor cambia mucho de nivel de dificultad  :  0  :  0
Magnitud de movimiento constante que mantiene un objeto al moverse de un punto a otro.  :  0  :  0